### ISSUE TITLE
Registry information for version check does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#105]
Test version: v1.9.1

Procedure
Add "URLCheckLatestVersion" to the registry.
data is "https://www.psn-web.net/ssbu-t/temp/ActiveGuard/LatestVersion.xml",  this is dummy URL only for our testing. 

![image](https://github.com/user-attachments/assets/219c5bec-52d4-481a-b48d-b1ddb08b44c7)

Phenomenon
It seems plug-in does not use this registry information.
Please let us know if our test procedure is not correct.
I do not remember your final implementation to this topic.

@alexnaicuorbnet

**Comment by alexnaicuorbnet** [comment]
Yes, that part was made not with registry information but with a txt file URLCheckLatestVersion.txt in the ProgramData/i-PRO/i-PRO Active Guard folder on the event server machine. If that file exists then it uses the link from that file, otherwise it uses the default https://www.psn-web.net/ssbu-t/Useful_tool/ActiveGuard/LatestVersion.xml

This can be tested on the current version v.1.9.1

![image](https://github.com/user-attachments/assets/c85b5449-1fe1-41f6-981b-1c35174424d0)

**Comment by Yoshitaka-Fukushima** [comment]
@alexnaicuorbnet 
Thank you, we could test more.
