### ISSUE TITLE
Roles configuration does not work

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#97]
Test version: v1.6.5

When uninstalling previous plugin version and install v1.6.5.
Management client shows as follows.

**Issue 1**
 If the word "ORBNET Tools Config Node" is not intended, it should be "i-PRO Active Guard".

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/755d131b-e8cb-491c-b076-e0265dfef23d)
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/857bca9c-735f-4e53-94fb-80e5f9d73a79)

**Issue 2:**

When log-in Smart Client with this role user, Active Guard plug-in tab is not shown though "Disable Smart Client  access" is unchecked.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/1e44819c-3738-41a7-8dcf-8b38077215a9)

@alexnaicuorbnet  @EricBourque

**Comment by EricBourque** [comment]
Issue1: 
Sorry, this is caused by old version of OSS plugin. The item node had the wrong name and now it is stuck.
This issue will not happen when installing on new server.
To fix this, you must delete the item node in SQL Database and re-open the Management Client.
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/65533203/64084f98-eee6-4d37-aa0e-7f1122c6e6eb)

Issue2: 
I found the cause of the issue.
We did not know this behavior, but Milestone uses in the background GENERIC_READ to decide which users are allowed to read the item. Once the item has been read, we can then check the other fields like Disable Smart Client and camera access.

In your current version, it should work if you set the read on "Overall Security" to checked.
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/65533203/7591bc93-1ba6-42e0-9ee6-4757095fca5a)

In 1.6.6, I have added "Read (required, please check)" so you can try it out.
Please let me know if you want to change anything.
![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/65533203/2dc7b99b-9236-4f18-99ea-979b2e5d1202)

I will check with Milestone if there is a way to initialize READ to True for all new roles, but I doubt it.
So it looks like in the end, inverting the value to give users a better experience may not be possible at this time and the GENERIC_READ must be checked for any kind of security options to work.

Please find v1.6.6 installer in the sharepoint.

**Comment by Yoshitaka-Fukushima** [comment]
Thanks to clarify many thing. @EricBourque 
Issue 1 was solved by deleting database and then install v1.6.6.

For issue2,  I assume if user update from v1,5 to new version, not Administrator never can use Active Guard before checking "Read" option, which may cause many inquiries from the market.

This is the default value for Axis optimizer. Two options are enabled.
I would like to wait Milestone SDK team answer.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/714de0b5-e3c2-4445-bc17-60cfff76d494)
